version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  seleniumscripts:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=sample.xml
    volumes:
    - ./output:/app/test-output